# 4th do deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uf-maha-pg
  labels:
    #name: uf-maha-pg
    app: uf-maha-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      #run: uf-maha-pg
      app: uf-maha-pg
  template:
    metadata:
      labels:
        #run: uf-maha-pg
        app: uf-maha-pg
    spec:
      containers:
      - name: postgres
        image: postgres:14.4
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
            name: uf-maha-pg
        #env:
          #- name: POSTGRES_DB
            #value: uf_maha
          #- name: POSTGRES_USER
            #value: postgres
          #- name: POSTGRES_PASSWORD
            #value: postgres
        envFrom:
          - configMapRef:
              name: uf-maha-pg-config
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgredb-maha
      volumes:
        - name: postgredb-maha
          persistentVolumeClaim:
            claimName: uf-maha-postgres-data-claim

---
# 5th create service
apiVersion: v1
kind: Service
metadata:
  name: uf-maha-pg       # Name of the resource
  labels:                 # Labels that will be applied to the resource
    app: uf-maha-pg
spec:
  #type: LoadBalancer
  #type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: uf-maha-pg
    #tier: postgres
