apiVersion: v1
kind: ConfigMap
metadata:
  name: uf-maha-pg-config
  labels:
    app: uf-maha-pg
data:
  POSTGRES_DB: uf_maha
  POSTGRES_USER: postgres 
  POSTGRES_PASSWORD: postgres 
  #POSTGRES_HOST_AUTH_METHOD: trust
