apiVersion: v1
kind: Service
metadata:
  name: uf-public
  #labels:
    #run: uf-public
spec:
  type: LoadBalancer
  selector:
    app: uf-public
  ports:
  - name: http
    protocol: TCP
    port: 8050
    targetPort: 8050
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  externalTrafficPolicy: Local
