apiVersion: apps/v1
kind: Deployment
metadata:
  name: uf-aim-deployment
  labels:
    name: uf-aim
    #app: uf-aim-app
spec:
  replicas: 2
  selector:
    matchLabels:
      #app: uf-aim-app
      run: uf-aim
  template:
    metadata:
      labels:
        #app: uf-aim-app
        run: uf-aim
    spec:
      containers:
      - name: uf-aim-app
        image: docker.io/gronka/uf_aim:v0.2
        ports:
        - containerPort: 8030
---
apiVersion: v1
kind: Service
metadata:
  name: uf-aim
  labels:
    run: uf-aim
spec:
  selector:
    app.kubernetes.io/name: uf-aim
    run: uf-aim
  ports:
  - protocol: TCP
    port: 8030
    targetPort: 8030
  type: LoadBalancer
  externalTrafficPolicy: Local
