apiVersion: apps/v1
kind: Deployment
metadata:
  name: uf-order-deployment
  labels:
    name: uf-order
    #app: uf-order-app
spec:
  replicas: 2
  selector:
    matchLabels:
      #app: uf-order-app
      run: uf-order
  template:
    metadata:
      labels:
        #app: uf-order-app
        run: uf-order
    spec:
      containers:
      - name: uf-order-app
        image: docker.io/gronka/uf_order:v0.2
        ports:
        - containerPort: 8040
---
apiVersion: v1
kind: Service
metadata:
  name: uf-order
  labels:
    run: uf-order
spec:
  selector:
    app.kubernetes.io/name: uf-order
    run: uf-order
  ports:
  - protocol: TCP
    port: 8040
    targetPort: 8040
  type: LoadBalancer
  externalTrafficPolicy: Local
