apiVersion: apps/v1
kind: Deployment
metadata:
  name: uf-public-deployment
  labels:
    name: uf-public
    #app: uf-public-app
spec:
  replicas: 2
  selector:
    matchLabels:
      #app: uf-public-app
      run: uf-public
  template:
    metadata:
      labels:
        #app: uf-public-app
        run: uf-public
    spec:
      containers:
      - name: uf-public-app
        image: docker.io/gronka/uf_public:v0.2
        ports:
        - containerPort: 8050
---
apiVersion: v1
kind: Service
metadata:
  name: uf-public
  labels:
    run: uf-public
spec:
  selector:
    app.kubernetes.io/name: uf-public
    run: uf-public
  ports:
  - protocol: TCP
    port: 8050
    targetPort: 8050
  type: LoadBalancer
  externalTrafficPolicy: Local
