# config for all services
apiVersion: v1
kind: ConfigMap
metadata:
  name: uno-global-config-prod
data:
  Environment: "prod"
  AmazonEmail: ""
  AmazonPassword: ""
  ApiDn: "https://api.cheese.rodeo"
  AppDn: "https://cheese.rodeo"
  FridayyPhone: "1234567890"
  HushJwt: "this is the key used for internet comm"
  LoggingLevel: "0"
  LoopAuthorization: ""
  LoopHookAuthorization: ""
  LoopSecretKey: ""
  OpenAiKey: ""
  SendBlueApiKeyId: ""
  SendBlueApiSecret: ""
  SendBlueHookSecret: ""
  SipHookSecret: ""
  SipUrl: ""
  SmtpHost: ""
  SmtpPort: "465"
  SmtpUser: ""
  SmtpPass: ""
  StripePublicKey: ""
  StripeSecretKey: ""
  TelegramBotId: ""
  TelegramChannelId: ""
  UfKey: "simplekey"
  UfScheme: "http"
  UspsUsername: ""
  UspsPassword: ""
  ZincCardName: ""
  ZincCardNumber: ""
  ZincCardExpirationMonth: ""
  ZincCardExpirationYear: ""
  ZincCardSecurityCode: ""
  ZincToken: ""
