apiVersion: apps/v1
kind: Deployment
metadata:
  name: uf-border-deployment
  labels:
    name: uf-border
    #app: uf-border-app
spec:
  replicas: 2
  selector:
    matchLabels:
      #app: uf-border-app
      run: uf-border
  template:
    metadata:
      labels:
        #app: uf-border-app
        run: uf-border
    spec:
      containers:
      - name: uf-border-app
        image: docker.io/gronka/uf_border:v0.2
        ports:
        - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: uf-border
  labels:
    run: uf-border
spec:
  selector:
    app.kubernetes.io/name: uf-border
    run: uf-border
  ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
  type: LoadBalancer
  externalTrafficPolicy: Local
