apiVersion: v1
kind: ConfigMap
metadata:
  name: uf-order-pg-config
  labels:
    app: uf-order-pg
data:
  POSTGRES_DB: uf_order
  POSTGRES_USER: postgres 
  POSTGRES_PASSWORD: postgres 
  POSTGRES_HOST_AUTH_METHOD: trust
